export const Categories = [
  {
    name: "Suv",
    image: require("./images/suv/audiQ7suv.png"),
    items: [
      {
        name: "Audi Q7",
        year: 2023,
        rating: "5.0",
        condition: "NEW",
        price: 60000,
        isTopOfTheWeek: true,
        image: require("./images/suv/audiQ7suv.png"),
        classe: "Suv",
        description:
          "The Audi Q7 is getting an all-round update – both visually and technically. The large SUV features the new design of the Q family and offers superb dynamics and excellent comfort, in addition to its superior spaciousness.",
      },
      {
        name: "BWM X6",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 71000,
        isTopOfTheWeek: true,
        image: require("./images/suv/bmwx6.png"),
        classe: "Suv",
        description:
          "The BMW X6 is a fastback “four-door coupe” version of the X5 mid-size luxury SUV, with seating for five. X6 powertrain choices include a 335-horsepower, turbocharged 3.0-liter inline-six engine or a 523-hp, twin-turbocharged 4.4-liter V-8.",
      },
      {
        name: "Hyndai Santa Fe",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 32450,
        isTopOfTheWeek: true,
        image: require("./images/suv/hyundaisuv.png"),
        classe: "Suv",
        description:
          "The Santa Fe delivers impressive acceleration and fuel efficiency as well as luxurious accommodations at a price that undercuts most of the competition. A spacious cabin and a smooth ride quality are also highlights.",
      },
      {
        name: "Kia Sportage",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 28000,
        isTopOfTheWeek: true,
        image: require("./images/suv/kiasuv.png"),
        classe: "Suv",
        description:
          "The 2023 Kia Sportage Hybrid comes in three trims: LX, EX and SX Prestige. All models come with a turbocharged four-cylinder engine, an electric motor and a six-speed automatic transmission.",
      },
      {
        name: "Mercedes-AMG",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 78000,
        isTopOfTheWeek: true,
        image: require("./images/suv/mercedes.png"),
        classe: "Suv",
        description:
          "The 2023 Mercedes-AMG® GLE offers rear-wheel drive with 3. According to the manufacturer, the 2023 Mercedes-Benz GLE is capable of 0 - 60 mph in 6.9 seconds and a top speed of 155 mph.",
      },
      {
        name: "Porsche Cayenne",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 73650,
        isTopOfTheWeek: true,
        image: require("./images/suv/porschesuv.png"),
        classe: "Suv",
        description:
          "This plug-in hybrid version of the Cayenne builds on the base model's features with: Turbocharged 3.0-liter six-cylinder engine and electric motor (455 total hp, 516 lb-ft)",
      },
    ],
  },
  {
    name: "Coupe",
    image: require("./images/coupe/mercedezcoupe.png"),
    items: [
      {
        name: "Chevrolet Camaro",
        year: 2023,
        rating: "5.0",
        condition: "NEW",
        price: 75395,
        isTopOfTheWeek: true,
        image: require("./images/coupe/ChevroletCamaroZL1.png"),
        classe: "Coupe",
        description:
          "The package's wider and stickier tires, manually adjustable front suspension, and exclusive spool-valve dampers help chew up racetracks and spit out happy drivers. ",
      },
      {
        name: "BMW 840i",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 87500,
        isTopOfTheWeek: true,
        image: require("./images/coupe/bmwcoupe.png"),
        classe: "Coupe",
        description:
          "BMW's biggest coupe and convertible start off with a 335-hp turbocharged inline-six-cylinder. These 840i models pair with an eight-speed automatic transmission.",
      },
      {
        name: "Audi RS5",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 79695,
        isTopOfTheWeek: true,
        image: require("./images/coupe/audi.png"),
        classe: "Coupe",
        description:
          "The 2023 Audi RS5 is a mouthy all-wheel-drive sports coupe with elegant proportions and a refined 444-hp twin-turbo V-6. As the wildest version of the A5 and S5 coupes, the RS5 also has the widest, stickiest tires, and biggest brakes.",
      },
      {
        name: "Jaguar F-TYPE",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 75395,
        isTopOfTheWeek: true,
        image: require("./images/coupe/jaguarcoupe.png"),
        classe: "Coupe",
        description:
          "The 2023 F-type offers everything you'd expect from a Jaguar sports car: a beautiful design, a sonorous engine, and plenty of driving character.",
      },
      {
        name: "Mercedes-Benz",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 63590,
        isTopOfTheWeek: true,
        image: require("./images/coupe/mercedezcoupe.png"),
        classe: "Coupe",
        description:
          "It is available with Automatic transmission. Depending upon the variant and fuel type the C-Class has a mileage of 23.0 kmpl .",
      },
      {
        name: "Porsche 718",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 63400,
        isTopOfTheWeek: true,
        image: require("./images/coupe/porschecoupe.png"),
        classe: "Coupe",
        description:
          "Combined with PDK: 430Nm. The sprint from 0 to 100km/h: 4.0 seconds when combined with PDK and Launch Control. Top speed: 288km/h. Combined with 6-speed manual transmission, it can even reach 293km/h.",
      },
    ],
  },
  {
    name: "Hatchback",
    image: require("./images/hatchback/hyundai.png"),
    items: [
      {
        name: "Renault Megane",
        year: 2023,
        rating: "5.0",
        condition: "NEW",
        price: 26000,
        isTopOfTheWeek: true,
        image: require("./images/hatchback/reno.png"),
        classe: "Hatchback",
        description:
          "The Megane R.S. Trophy is a front wheel drive 5 door with 5 seats, powered by a 1.8L TURBO 4 engine that has 221 kW of power (at 6000 rpm) and 400 Nm of torque (at 3200 rpm) via a Six-speed Manual.",
      },
      {
        name: "BMW M135i",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 49900,
        isTopOfTheWeek: true,
        image: require("./images/hatchback/bmw.png"),
        classe: "Hatchback",
        description:
          "The 1 Series is an all wheel drive 5 door with 5 seats, powered by a 2.0L TURBO 4 engine that has 225 kW of power (at 5000 rpm) and 450 Nm of torque (at 1800 rpm) via an Eight-speed Auto Steptronic Sprt.",
      },
      {
        name: "Ford Fiesta",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 33490,
        isTopOfTheWeek: true,
        image: require("./images/hatchback/fordfiesta.png"),
        classe: "Hatchback",
        description:
          "The Fiesta is a front wheel drive 5 door with 5 seats, powered by a 1.5L TURBO 3 engine that has 147 kW of power (at 6000 rpm) and 320 Nm of torque (at 4500 rpm) via a Six-speed Manual.",
      },
      {
        name: "Hyundai i30",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 23720,
        isTopOfTheWeek: true,
        image: require("./images/hatchback/hyundai.png"),
        classe: "Hatchback",
        description:
          "The i30 is a front wheel drive 5 door with 5 seats, powered by a 2.0L INLINE 4 engine that has 120 kW of power (at 6200 rpm) and 203 Nm of torque (at 4700 rpm) via a Six-speed Manual",
      },
      {
        name: "Mazda 3",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 23715,
        isTopOfTheWeek: true,
        image: require("./images/hatchback/mazda.png"),
        classe: "Hatchback",
        description:
          "A 2.5L turbo engine is available and offers up to 250 hp 5 and 320 lb-ft of torque. Mazda3 2.5 Turbo Sedan models also come standard with our i-Activ AWD® which constantly directs torque to the tires with the most grip to help optimize performance in nearly any weather.",
      },
      {
        name: "Toyota Corolla",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 26700,
        isTopOfTheWeek: true,
        image: require("./images/hatchback/toyota.png"),
        classe: "Hatchback",
        description:
          "The 12th-generation Toyota Corolla offers impressive fuel efficiency and an abundance of standard safety features in a compact package that looks far more exciting than it is to drive.",
      },
    ],
  },
  {
    name: "Sports Car",
    image: require("./images/sportscar/lambo.png"),
    items: [
      {
        name: "Bugati Chiron",
        year: 2023,
        rating: "5.0",
        condition: "NEW",
        price: 3000000,
        isTopOfTheWeek: true,
        image: require("./images/sportscar/bugati.png"),
        classe: "Sports Car",
        description:
          "All 2023 Bugatti Chiron models are powered by an 8.0-liter 16-cylinder engine. This engine uses four turbochargers to produce 1,500 horsepower and 1,180 kg of torque.",
      },
      {
        name: "Aston Martin",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 2300000,
        isTopOfTheWeek: true,
        image: require("./images/sportscar/astonmartin.png"),
        classe: "Sports Car",
        description:
          "The top speed (without the wing) is 208 mph (335 km/h) and 0-60 time is 2.9 seconds. The Vulcan is fitted with a magnesium torque tube which has a carbon fibre propeller shaft...",
      },
      {
        name: "Ferrari 812 GTS",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 440000,
        isTopOfTheWeek: true,
        image: require("./images/sportscar/ferrari.png"),
        classe: "Sports Car",
        description:
          "With a naturally-aspirated V12 engine hidden in its long and unmistakably aggressive front-end, the Ferrari 812 GTS is the convertible version of Ferrari's 812 Superfast.",
      },
      {
        name: "Lamborghini",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 825914,
        isTopOfTheWeek: true,
        image: require("./images/sportscar/lambo.png"),
        classe: "Sports Car",
        description:
          "The Aventador is an all wheel drive 2 door with 2 seats, powered by a 6.5L V12 engine that has 544 kW of power (at 8400 rpm) and 690 Nm of torque (at 5500 rpm) via a Seven-speed Automated Manual.",
      },
      {
        name: "Pagani Huayra",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 1400000,
        isTopOfTheWeek: true,
        image: require("./images/sportscar/pagani.png"),
        classe: "Sports Car",
        description:
          "The Pagani Huayra 2023 is hypercar that is finely crafted, with mill metric precision used in the production of every component and panel.",
      },
      {
        name: "Koenigsegg CC850",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 3100000,
        isTopOfTheWeek: true,
        image: require("./images/sportscar/Koenigsegg.png"),
        classe: "Sports Car",
        description:
          "Being a Koenigsegg, the CC850 has many other talents beyond its outrageous gearbox. It makes 1,353 horsepower from a 5.0-liter twin-turbocharged V8 borrowed from the Jesko.",
      },
    ],
  },
  {
    name: "Pickup Truck",
    image: require("./images/pickuptruck/fordrangerrapotr.png"),
    items: [
      {
        name: "Ford Ranger",
        year: 2023,
        rating: "5.0",
        condition: "NEW",
        price: 43615,
        isTopOfTheWeek: true,
        image: require("./images/pickuptruck/fordrangerrapotr.png"),
        classe: "Pickup Truck",
        description:
          "The Ranger is a four wheel drive 4 door with 5 seats, powered by a 3.0L TWIN TURBO V6 engine that has 292 kW of power (at 5650 rpm) and 583 Nm of torque (at 1750 rpm) via a Ten-speed Automatic.",
      },
      {
        name: "GMC HUMMER EV",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 98845,
        isTopOfTheWeek: true,
        image: require("./images/pickuptruck/gmchummer.webp"),
        classe: "Pickup Truck",
        description:
          "The GMC Hummer EV is an absolutely bonkers pickup truck. Not only is it gargantuan and impressively heavy, but it's monstrously quick and surprisingly capable. Despite weighing in at about 4.5 tons, it rockets from 0-60 mph with supercar-rivaling aggression, hitting the benchmark speed in 3.0 seconds.",
      },
      {
        name: "Isuzu D-MAX",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 32200,
        isTopOfTheWeek: true,
        image: require("./images/pickuptruck/isuzu.png"),
        classe: "Pickup Truck",
        description:
          "The D-Max is a four-wheel drive 4 door with 5 seats, powered by a 3.0L DIESEL TURBO 4 engine that has 140 kW of power (at 3600 rpm) and 450 Nm of torque (at 1600 rpm) via a 6 SP AUTO SEQ SPORTS MODE.",
      },
      {
        name: "Peugeot Landtrek",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 33020,
        isTopOfTheWeek: true,
        image: require("./images/pickuptruck/peugeotlandtrek.png"),
        classe: "Pickup Truck",
        description:
          "Peugeot Landtrek 2023 is available with 6-Speed AT transmission. The Peugeot Landtrek 2023 is a 5 Seater Pickup whose kerb weight 2095 Kg. In configurations, Peugeot Landtrek 2023 has a length of 5331 mm, the width of 1925 mm, the height of 1877 mm, a wheelbase of 3180 mm and 235 mm ground clearance.",
      },
      {
        name: "Ssangyong Musso",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 36790,
        isTopOfTheWeek: true,
        image: require("./images/pickuptruck/ssangyongmusso.png"),
        classe: "Pickup Truck",
        description:
          "The Musso is a four wheel drive 4 door with 5 seats, powered by a 2.2L DIESEL TURBO 4 engine that has 133 kW of power (at 4000 rpm) and 420 Nm of torque (at 1600 rpm) via a Six-speed Automatic.",
      },
      {
        name: "Toyota Hilux GR-S",
        year: 2023,
        condition: "NEW",
        rating: "5.0",
        price: 43615,
        isTopOfTheWeek: true,
        image: require("./images/pickuptruck/toyota.png"),
        classe: "Pickup Truck",
        description:
          "At the heart of this Hilux lies a 2.8-liter turbodiesel capable of 221hp and 550Nm, fitted to an automatic transmission with “sportier tuning” and paddle shifters. Other mechanical bits on this double-cab pickup include monotube shock absorbers and stiff coil springs.",
      },
    ],
  },
];
